service: Weather

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

functions:
  weather:
    handler: function.getWeather
    events:
      - http:
          path: weather
          method: get
          cors: true